import sqlmodel
"""init

Revision ID: 174e44a671f1
Revises: 
Create Date: 2026-07-19 12:31:34.159829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174e44a671f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'apply_url', name='uq_platform_url')
    )
    op.create_index(op.f('ix_applications_platform'), 'applications', ['platform'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('headless', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_queue_platform'), 'job_queue', ['platform'], unique=False)
    op.create_index(op.f('ix_job_queue_status'), 'job_queue', ['status'], unique=False)
    op.create_index(op.f('ix_job_queue_user_id'), 'job_queue', ['user_id'], unique=False)
    op.create_table('run_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_events_user_id'), 'run_events', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('run_interval_hours', sa.Integer(), nullable=False),
    sa.Column('max_applies_per_run', sa.Integer(), nullable=False),
    sa.Column('next_run', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_platform'), 'schedules', ['platform'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iv', sa.JSON(), nullable=True),
    sa.Column('encrypted_blob', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_platform'), 'sessions', ['platform'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('college', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cgpa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resume_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('github', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('achievement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_preferences', sa.JSON(), nullable=True),
    sa.Column('exclude_keywords', sa.JSON(), nullable=True),
    sa.Column('years_of_experience', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notice_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_ctc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_ctc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('willing_to_relocate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferred_mode', sa.JSON(), nullable=True),
    sa.Column('open_to_hybrid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_authorization', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internshala_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linkedin_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('naukri_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unstop_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_platform'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_platform'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_run_events_user_id'), table_name='run_events')
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_job_queue_user_id'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_status'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_platform'), table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_platform'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
